# Generated by Django 4.1.7 on 2023-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='property_value',
            field=models.ManyToManyField(blank=True, related_name='product_version', to='product.propertyvalue'),
        ),
    ]
