# Generated by Django 4.1.7 on 2023-07-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productversion_property_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='png',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='product.category'),
        ),
    ]
