# Generated by Django 4.1.7 on 2023-07-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('profession', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('information', models.TextField()),
                ('facebook_account', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('instagram_account', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('twitter_account', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('google_account', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
